// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Config = __t.object("Config", {
  version: __t.u32(),
  worldWidth: __t.u32(),
  worldHeight: __t.u32(),
  lastTick: __t.u64(),
});
export type Config = __Infer<typeof Config>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  resources: __t.u32(),
  online: __t.bool(),
});
export type Player = __Infer<typeof Player>;

export const Unit = __t.object("Unit", {
  id: __t.u64(),
  owner: __t.identity(),
  unitType: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  targetX: __t.f32(),
  targetY: __t.f32(),
  speed: __t.f32(),
  moving: __t.bool(),
  pendingTargetX: __t.f32(),
  pendingTargetY: __t.f32(),
  pendingStartTick: __t.u64(),
});
export type Unit = __Infer<typeof Unit>;

export const Waypoint = __t.object("Waypoint", {
  id: __t.u64(),
  unitId: __t.u64(),
  x: __t.f32(),
  y: __t.f32(),
  order: __t.u32(),
});
export type Waypoint = __Infer<typeof Waypoint>;

