// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Order,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  matchId: __t.u64().name("match_id"),
  issuer: __t.identity(),
  requestId: __t.string().name("request_id"),
  owner: __t.u8(),
  units: __t.array(__t.u32()),
  get order() {
    return Order;
  },
  queued: __t.bool(),
  issuedTick: __t.u64().name("issued_tick"),
  executeTick: __t.u64().name("execute_tick"),
  status: __t.string(),
  reason: __t.string(),
});
