// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  matchId: __t.u64().name("match_id"),
  tick: __t.u64(),
  slot: __t.u8(),
  material: __t.u32(),
  catalyst: __t.u32(),
  collectedMaterial: __t.u32().name("collected_material"),
  collectedCatalyst: __t.u32().name("collected_catalyst"),
  armyValueMaterial: __t.u32().name("army_value_material"),
  armyValueCatalyst: __t.u32().name("army_value_catalyst"),
  labour: __t.u32(),
  army: __t.u32(),
  buildings: __t.u32(),
  lostMaterial: __t.u32().name("lost_material"),
  lostCatalyst: __t.u32().name("lost_catalyst"),
});
