// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.u64().primaryKey(),
  matchId: __t.u64().name("match_id"),
  id: __t.u32(),
  owner: __t.u8(),
  tactic: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  size: __t.i32(),
  state: __t.string(),
  stateTick: __t.u64().name("state_tick"),
  rallyX: __t.f32().name("rally_x"),
  rallyY: __t.f32().name("rally_y"),
  gatherPercent: __t.u8().name("gather_percent"),
  fallbackPercent: __t.u8().name("fallback_percent"),
  strikeStrength: __t.u32().name("strike_strength"),
  members: __t.array(__t.u32()),
});
