// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Faction,
} from "./types";


export default __t.row({
  identity: __t.identity().primaryKey(),
  matchId: __t.u64().name("match_id"),
  name: __t.string(),
  slot: __t.u8(),
  material: __t.u32(),
  catalyst: __t.u32(),
  collectedMaterial: __t.u32().name("collected_material"),
  collectedCatalyst: __t.u32().name("collected_catalyst"),
  lostMaterial: __t.u32().name("lost_material"),
  lostCatalyst: __t.u32().name("lost_catalyst"),
  killedMaterial: __t.u32().name("killed_material"),
  killedCatalyst: __t.u32().name("killed_catalyst"),
  get faction() {
    return Faction;
  },
  research: __t.array(__t.string()),
  ready: __t.bool(),
  online: __t.bool(),
  lastOrderTick: __t.u64().name("last_order_tick"),
  ordersThisTick: __t.u32().name("orders_this_tick"),
});
