// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  host: __t.identity(),
  capacity: __t.u8(),
  state: __t.string(),
  tick: __t.u64(),
  commandDelay: __t.u64().name("command_delay"),
  rulesetVersion: __t.u32().name("ruleset_version"),
  mapId: __t.string().name("map_id"),
  mapVersion: __t.u32().name("map_version"),
  mapHash: __t.u64().name("map_hash"),
  nextEntityId: __t.u32().name("next_entity_id"),
  winner: __t.i16(),
  lastActivityMicros: __t.i64().name("last_activity_micros"),
});
