// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Command = __t.object("Command", {
  id: __t.u64(),
  matchId: __t.u64(),
  issuer: __t.identity(),
  requestId: __t.string(),
  owner: __t.u8(),
  units: __t.array(__t.u32()),
  get order() {
    return Order;
  },
  queued: __t.bool(),
  issuedTick: __t.u64(),
  executeTick: __t.u64(),
  status: __t.string(),
  reason: __t.string(),
});
export type Command = __Infer<typeof Command>;

export const Connection = __t.object("Connection", {
  id: __t.connectionId(),
  identity: __t.identity(),
});
export type Connection = __Infer<typeof Connection>;

export const CreepPatch = __t.object("CreepPatch", {
  source: __t.u32(),
  owner: __t.u8(),
  x: __t.f32(),
  y: __t.f32(),
  radius: __t.u16(),
  maxRadius: __t.u16(),
  lostTick: __t.u64(),
});
export type CreepPatch = __Infer<typeof CreepPatch>;

export const CreepPatchRow = __t.object("CreepPatchRow", {
  id: __t.u64(),
  matchId: __t.u64(),
  get data() {
    return CreepPatch;
  },
});
export type CreepPatchRow = __Infer<typeof CreepPatchRow>;

export const Entity = __t.object("Entity", {
  id: __t.u32(),
  owner: __t.u8(),
  kind: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  hp: __t.i32(),
  get order() {
    return Order;
  },
  get queue() {
    return __t.array(Order);
  },
  cargo: __t.u32(),
  get cargoKind() {
    return ResourceKind;
  },
  returning: __t.bool(),
  nextAttack: __t.u64(),
  shotTick: __t.u64(),
  shotX: __t.f32(),
  shotY: __t.f32(),
  get production() {
    return __t.array(Production);
  },
  constructionRemaining: __t.u64(),
  research: __t.array(__t.string()),
  stock: __t.u32(),
  expiresTick: __t.u64(),
  maxHp: __t.i32(),
  shields: __t.i32(),
  maxShields: __t.i32(),
  damagedTick: __t.u64(),
  warpTick: __t.u64(),
  arriveTick: __t.u64(),
});
export type Entity = __Infer<typeof Entity>;

// The tagged union or sum type for the algebraic type `Faction`.
export const Faction = __t.enum("Faction", {
  Industrial: __t.unit(),
  Network: __t.unit(),
  Organic: __t.unit(),
});
export type Faction = __Infer<typeof Faction>;

export const MatchSample = __t.object("MatchSample", {
  id: __t.u64(),
  matchId: __t.u64(),
  tick: __t.u64(),
  slot: __t.u8(),
  material: __t.u32(),
  catalyst: __t.u32(),
  collectedMaterial: __t.u32(),
  collectedCatalyst: __t.u32(),
  armyValueMaterial: __t.u32(),
  armyValueCatalyst: __t.u32(),
  labour: __t.u32(),
  army: __t.u32(),
  buildings: __t.u32(),
  lostMaterial: __t.u32(),
  lostCatalyst: __t.u32(),
});
export type MatchSample = __Infer<typeof MatchSample>;

export const Node = __t.object("Node", {
  id: __t.u32(),
  x: __t.f32(),
  y: __t.f32(),
  amount: __t.u32(),
  get kind() {
    return ResourceKind;
  },
});
export type Node = __Infer<typeof Node>;

export const Order = __t.object("Order", {
  kind: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  target: __t.u32(),
});
export type Order = __Infer<typeof Order>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  matchId: __t.u64(),
  name: __t.string(),
  slot: __t.u8(),
  material: __t.u32(),
  catalyst: __t.u32(),
  collectedMaterial: __t.u32(),
  collectedCatalyst: __t.u32(),
  lostMaterial: __t.u32(),
  lostCatalyst: __t.u32(),
  killedMaterial: __t.u32(),
  killedCatalyst: __t.u32(),
  get faction() {
    return Faction;
  },
  ready: __t.bool(),
  online: __t.bool(),
  lastOrderTick: __t.u64(),
  ordersThisTick: __t.u32(),
});
export type Player = __Infer<typeof Player>;

export const Production = __t.object("Production", {
  kind: __t.string(),
  finishTick: __t.u64(),
});
export type Production = __Infer<typeof Production>;

// The tagged union or sum type for the algebraic type `ResourceKind`.
export const ResourceKind = __t.enum("ResourceKind", {
  Material: __t.unit(),
  Catalyst: __t.unit(),
});
export type ResourceKind = __Infer<typeof ResourceKind>;

export const ResourceNode = __t.object("ResourceNode", {
  id: __t.u64(),
  matchId: __t.u64(),
  get data() {
    return Node;
  },
});
export type ResourceNode = __Infer<typeof ResourceNode>;

export const Room = __t.object("Room", {
  id: __t.u64(),
  name: __t.string(),
  host: __t.identity(),
  capacity: __t.u8(),
  state: __t.string(),
  tick: __t.u64(),
  commandDelay: __t.u64(),
  rulesetVersion: __t.u32(),
  mapId: __t.string(),
  mapVersion: __t.u32(),
  mapHash: __t.u64(),
  nextEntityId: __t.u32(),
  winner: __t.i16(),
  lastActivityMicros: __t.i64(),
  lastTickMicros: __t.i64(),
});
export type Room = __Infer<typeof Room>;

export const TickSchedule = __t.object("TickSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickSchedule = __Infer<typeof TickSchedule>;

export const Unit = __t.object("Unit", {
  id: __t.u64(),
  matchId: __t.u64(),
  get data() {
    return Entity;
  },
});
export type Unit = __Infer<typeof Unit>;

