// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  unitType: __t.string().name("unit_type"),
  x: __t.f32(),
  y: __t.f32(),
  targetX: __t.f32().name("target_x"),
  targetY: __t.f32().name("target_y"),
  speed: __t.f32(),
  moving: __t.bool(),
  pendingTargetX: __t.f32().name("pending_target_x"),
  pendingTargetY: __t.f32().name("pending_target_y"),
  pendingStartTick: __t.u64().name("pending_start_tick"),
});
