// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import BuildBuildingReducer from "../build_building_reducer";
import JoinMatchReducer from "../join_match_reducer";
import MoveUnitReducer from "../move_unit_reducer";
import ResetGameReducer from "../reset_game_reducer";
import SetNameReducer from "../set_name_reducer";
import StartMatchReducer from "../start_match_reducer";
import TrainUnitReducer from "../train_unit_reducer";

export type BuildBuildingParams = __Infer<typeof BuildBuildingReducer>;
export type JoinMatchParams = __Infer<typeof JoinMatchReducer>;
export type MoveUnitParams = __Infer<typeof MoveUnitReducer>;
export type ResetGameParams = __Infer<typeof ResetGameReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type StartMatchParams = __Infer<typeof StartMatchReducer>;
export type TrainUnitParams = __Infer<typeof TrainUnitReducer>;

