// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateRoomReducer from "../create_room_reducer";
import IssueOrderReducer from "../issue_order_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import SetNameReducer from "../set_name_reducer";
import SetReadyReducer from "../set_ready_reducer";
import StartMatchReducer from "../start_match_reducer";

export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type IssueOrderParams = __Infer<typeof IssueOrderReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type SetReadyParams = __Infer<typeof SetReadyReducer>;
export type StartMatchParams = __Infer<typeof StartMatchReducer>;

