// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import BuildBuildingReducer from "../build_building_reducer";
import GameTickReducer from "../game_tick_reducer";
import MoveUnitReducer from "../move_unit_reducer";
import ResetGameReducer from "../reset_game_reducer";
import TrainUnitReducer from "../train_unit_reducer";

export type BuildBuildingParams = __Infer<typeof BuildBuildingReducer>;
export type GameTickParams = __Infer<typeof GameTickReducer>;
export type MoveUnitParams = __Infer<typeof MoveUnitReducer>;
export type ResetGameParams = __Infer<typeof ResetGameReducer>;
export type TrainUnitParams = __Infer<typeof TrainUnitReducer>;

